### ISSUE TITLE
tests fail to build right after cloning a repo (missing nugetRestore step ?)

### ISSUE THREAD

**Issue by gwen-le-mero** [oliviergauthier/xam-gradle-plugins#1]
**FIRST!!!!!**

details:
doing gradle test just after clonign the repo provokes the issue.

if we manually do 'gradle nugetRestore' or 'gradle package', then doing 'gradle test' works fine and runs the tests normally.

**Comment by oliviergauthier** [comment]
Fixed in 0.2.5 ;-)

**Comment by gwen-le-mero** [comment]
thanks :)

*Gwenaël Le Méro*| Senior Engineer
BeTomorrow | 3 rue Lafayette - 33000 Bordeaux - France
Skype : gwen_le_mero
