### ISSUE TITLE
PDB files not included in NuGet packages

### ISSUE THREAD

**Issue by gmarrot** [oliviergauthier/xam-gradle-plugins#4]
.pdb files generated by projects are not included into NuGet packages built with the plugin.
It works with .mdb files.

It seems to be due to different naming conventions between .mdb and .pdb:
- For .mdb, Mono generates a <my_assembly_name>**.dll.mdb** file
- For .pdb, it generates a <my_assembly_name>**.pdb** file

**Comment by oliviergauthier** [comment]
Resolved in 0.3.3 ;-)
